# Form implementation generated from reading ui file '.\tespit.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtGui import QPixmap, QImage
from PyQt6.QtCore import QTimer


class Ui_MainWindow_Tespit(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(650, 640)
        MainWindow.setMinimumSize(QtCore.QSize(650, 640))
        MainWindow.setMaximumSize(QtCore.QSize(650, 640))

        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.video_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.video_label.setGeometry(QtCore.QRect(5, 5, 640, 480))
        self.video_label.setText("")
        self.video_label.setObjectName("label")

        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(5, 490, 640, 121))

        font = QtGui.QFont()
        font.setPointSize(32)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")

        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Tespit Ekranı - AEROKOU"))
        self.pushButton.setText(_translate("MainWindow", "HEDEFLER"))